### ISSUE TITLE
Vers 0.1.7 start task @tasker don´t work

### ISSUE THREAD

**Issue by Maja61** [bondrogeen/ioBroker.paw#11]
HI,

in the newest version 0.1.7 it is not possible to send tasker actions to the paw server verion 0.97.2 on android. 

used code on iobroker: 
`    sendTo("paw.0",'TabE',{
        send:  'task',
        text:'Display_aus',
    },function (response){
    log(JSON.stringify(response[0]));
});`

error message in iobroker log: 
`2017-11-07 14:42:07.418  - info: paw.0 <html>
bsh.EvalError: Sourced file: inline evaluation of: ``$$.print("<html>\n<body>\n"); import org.json.*; import de.fun2code.android.paws . . . '' : Attempt to resolve method: testStatus() on undefined variable or class name: TaskerIntent : at Line: 537 : in file: inline evaluation of: ``$$.print("<html>\n<body>\n"); import org.json.*; import de.fun2code.android.paws . . . '' : TaskerIntent .testStatus ( service )
`

works in vers 0.0.7 

regards.

**Comment by bondrogeen** [comment]
Tasker only works on and the iobroker.paw app
Android version is what?
https://yadi.sk/d/6iirDUxm3PYYN8

**Comment by bondrogeen** [comment]
0.0.7 and PAW Server worked if it was root
In the new version changed the work with the tasker

**Comment by bondrogeen** [comment]
sendTo("paw.0",'TabE',{send:'exec',text:'am broadcast -a net.dinglisch.android.tasker.ACTION_TASK -e task_name Display_aus'});
You can try this, but only if it's root
