### ISSUE TITLE
npm update ?!

### ISSUE THREAD

**Issue by Apollon77** [bondrogeen/ioBroker.paw#15]
npm is still 0.0.7 ... veerry old and buggy ... :-)

Thank you

**Comment by foxriver76** [comment]
@bondrogeen Great, that you keep working on the adapter. Would you be so kind and publish v0.2.0 on npm? Or are their any bigger issues with this version?

**Comment by bondrogeen** [comment]
I am still working on it, as soon as there is a stable version, I will immediately publish it.
