### ISSUE TITLE
parse data error

### ISSUE THREAD

**Issue by vr6syncro** [bondrogeen/ioBroker.paw#18]
https://forum.iobroker.net/viewtopic.php?f=24&t=6274&start=120

paw.0 | 2018-11-27 22:28:48.477 | info | parse_data_error:
-- | -- | -- | --

**Comment by bondrogeen** [comment]
The old version is no longer supported.

**Comment by vr6syncro** [comment]
what u mean with old version? its the latest adapter and no android paw updates

**Comment by bondrogeen** [comment]
> what u mean with old version?    

The old (v.0.0.7) version of the adapter is not supported.


New adapter version need new app!!!

This [new app](https://github.com/bondrogeen/ioBroker.paw/raw/master/app/app-release.apk) and  new **[ioBroker.paw 2 BETA](https://github.com/bondrogeen/ioBroker.paw)**  (Install from github) adapter ver >= 0.2.0

**Comment by vr6syncro** [comment]
Oh ok i Check that later. Thanks

**Comment by vr6syncro** [comment]
ok i tried it but i have some maybe issues.
first i cant get it to work with http connection and password. in iobroker i cant write a user/pass.
without i get a connection.
second on my iobroker with selected port i get 404 Error is that right?
third when i send logs in my app the app crash and reload.
and last it seems that only tablet infos are working but no commands.

**Comment by vr6syncro** [comment]
some logs:

paw.0 | 2018-11-29 19:38:56.357 | info | {"value":"-0.07182605","device":"Tablet","name":"accelerometerZ","namespace":"paw.0","path":"info.sensors.accelerometerZ"}
-- | -- | -- | --
paw.0 | 2018-11-29 19:38:56.357 | info | {"value":"0.17597382","device":"Tablet","name":"accelerometerY","namespace":"paw.0","path":"info.sensors.accelerometerY"}
paw.0 | 2018-11-29 19:38:56.357 | info | {"value":"9.516952","device":"Tablet","name":"accelerometerX","namespace":"paw.0","path":"info.sensors.accelerometerX"}
paw.0 | 2018-11-29 19:38:56.357 | info | {"value":"0.0","device":"Tablet","name":"light","namespace":"paw.0","path":"info.sensors.light"}
paw.0 | 2018-11-29 19:38:56.357 | debug | urlStr/api/
paw.0 | 2018-11-29 19:38:56.357 | debug | POST {"light":{"value":"0.0","device":"Tablet","name":"light","namespace":"paw.0","path":"info.sensors.light"},"accelerometerX":{"value":"9.516952","device":"Tablet","name":"accelerometerX","namespace
paw.0 | 2018-11-29 19:38:56.357 | debug | /api/
paw.0 | 2018-11-29 19:38:55.512 | info | {"value":"4.25","device":"Tablet","name":"voltage","namespace":"paw.0","path":"info.battery.voltage"}
paw.0 | 2018-11-29 19:38:55.512 | info | {"value":"AC","device":"Tablet","name":"type","namespace":"paw.0","path":"info.battery.type"}
paw.0 | 2018-11-29 19:38:55.511 | info | {"value":"24.0","device":"Tablet","name":"temperature","namespace":"paw.0","path":"info.battery.temperature"}
paw.0 | 2018-11-29 19:38:55.511 | info | {"value":"good","device":"Tablet","name":"health","namespace":"paw.0","path":"info.battery.health"}
paw.0 | 2018-11-29 19:38:55.511 | info | {"value":"100","device":"Tablet","name":"level","namespace":"paw.0","path":"info.battery.level"}
paw.0 | 2018-11-29 19:38:55.511 | debug | urlStr/api/
paw.0 | 2018-11-29 19:38:55.511 | debug | POST {"level":{"value":"100","device":"Tablet","name":"level","namespace":"paw.0","path":"info.battery.level"},"health":{"value":"good","device":"Tablet","name":"health","namespace":"paw.0","path":"in
paw.0 | 2018-11-29 19:38:55.511 | debug | /api/
paw.0 | 2018-11-29 19:38:32.851 | debug | objectItem [object Object]
paw.0 | 2018-11-29 19:38:30.649 | debug | /api/settings.json: Error: connect ECONNREFUSED 192.168.2.206:8080
paw.0 | 2018-11-29 19:38:30.625 | info | http server listening on port : 8898
paw.0 | 2018-11-29 19:38:30.625 | info | namespace: paw.0
paw.0 | 2018-11-29 19:38:30.625 | info | port: 8898
paw.0 | 2018-11-29 19:38:30.625 | info | server: 192.168.2.24
paw.0 | 2018-11-29 19:38:30.625 | info | interval: 60
paw.0 | 2018-11-29 19:38:30.625 | info | devices: [{"name":"Tablet","ip":"192.168.2.206","port":"8080","state":true}]
paw.0 | 2018-11-29 19:38:30.625 | debug | adapter.instance 0
paw.0 | 2018-11-29 19:38:30.624 | debug | getObjectItem
paw.0 | 2018-11-29 19:38:30.624 | info | starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.paw, node: v6.14.4
host.ioBroker | 2018-11-29 19:38:29.935 | info | instance system.adapter.paw.0 started with pid 25277

**Comment by bondrogeen** [comment]
What version of android?

If version> 6.0 may be a problem with permissions, I'm still working on it. Try to set all permissions through the phone settings and try to send the log again.
