### ISSUE TITLE
restore latest version <0.2.0 from somewwhere? (latest before was 0.1.7) not on npm

### ISSUE THREAD

**Issue by Apollon77** [bondrogeen/ioBroker.paw#26]
To introduce such a breaking change in a minor version change is very bad :-( Broke my whole display control because I did not saw it before and now I have no way to go back to 0.1.7 which was working perfectly for me!
0.0.7 (which is stable) is broken too because ignored the ack flag.

Can you somehow publish a 0.1.7 which was latest github before 0.2.0 to npm somehow? That would help very much!! And then please put this into "stable".

It should be that timepoint: https://github.com/bondrogeen/ioBroker.paw/tree/3f8843d01bf695884584f49fe21851495c681643

**Comment by bondrogeen** [comment]
Check it out.
Published npm version 0.1.7

**Comment by Apollon77** [comment]
thank you!
