### ISSUE TITLE
paw release.akp

### ISSUE THREAD

**Issue by MathiasJZ** [bondrogeen/ioBroker.paw#31]
Hi there,
Its not possible to install paw release app at my android  tablet PC.
I have android version 7.0.
To allow to install from unknown source its also impossible.
My Tablet can not open this akp file.
Greetings,
Mathias

**Comment by bondrogeen** [comment]
Send a screenshot of the screen and describe the problem in more detail.

**Comment by MathiasJZ** [comment]
Screenshot is not a problem.
But what more should I write?
Tablet cant open the akp file.
Thats all what I read also at the screen.
Greetings,
Mathias

Am 3. März 2019 10:42:42 schrieb Роман <notifications@github.com>:

**Comment by bondrogeen** [comment]
> It was possible with the app apk-installer.
> Without it it's impossible.

How do I understand the problem solved?

**Comment by MathiasJZ** [comment]
Problem is solved now.
But its possible to add it AG the readme?
Maybe others have the same problem?
Greetings,
Mathias

Am 3. März 2019 13:59:16 schrieb Роман <notifications@github.com>:

**Comment by bondrogeen** [comment]
Your problem is not related to the application.
