### ISSUE TITLE
iobroker.PAW II crash at autostart

### ISSUE THREAD

**Issue by RichieXX** [bondrogeen/ioBroker.paw#34]
iobroker.PAW II app crash when using autostart option. Maybe because the WLAN connection is not active yet. Is a delayed start possible?  When I start the app, it does'nt automatically connect to the iobroker server adapter. I have to select "Connection" first.

**Comment by bondrogeen** [comment]
There may be problems with the latest updates.
I will check and try to fix it.

Tell me the version of android and the type of connection (HTTP or MQTT)?

**Comment by RichieXX** [comment]
The android version is 8.1.0 (RR 6.2.1) on a N10. Connection type is HTTP.

**Comment by bondrogeen** [comment]
You can updated from Google Play

**Comment by RichieXX** [comment]
I have completely deinstalled, reinstalled the new and reconfigured app. Unfortunately, the same problem in the new version.

**Comment by bondrogeen** [comment]
Can you send me a log?

**Comment by RichieXX** [comment]
I'm not a github expert. Is there a private channel here for entire log?
Here are just a few parts of logcat:


`03-20 19:39:21.200 W/AppWidgetServiceImpl(340): No android.appwidget.provider meta-data for AppWidget provider 'ProviderId{user:0, app:10110, cmp:ComponentInfo{ru.codedevice.iobrokerpawii/ru.codedevice.iobrokerpawii.MainReceiver}}'
03-20 19:39:21.384 I/ActivityManager(340): Start proc 792:org.lineageos.audiofx/u0a2 for added application org.lineageos.audiofx
03-20 19:39:21.385 I/ActivityManager(340): User 0 state changed from RUNNING_UNLOCKING to RUNNING_UNLOCKED
03-20 19:39:21.386 I/ActivityManager(340): Sending BOOT_COMPLETE user #0
03-20 19:39:21.396 I/InputAttributes(751): InputType.TYPE_NULL is specified
03-20 19:39:21.420 I/main    (792): type=1400 audit(0.0:373): avc: denied { read } for name="u:object_r:wifi_prop:s0" dev="tmpfs" ino=4109 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:wifi_prop:s0 tclass=file permissive=1
03-20 19:39:21.425 I/main    (792): type=1400 audit(0.0:374): avc: denied { read } for name="u:object_r:theme_prop:s0" dev="tmpfs" ino=4113 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:theme_prop:s0 tclass=file permissive=1
03-20 19:39:21.425 I/main    (792): type=1400 audit(0.0:375): avc: denied { read } for name="u:object_r:firstboot_prop:s0" dev="tmpfs" ino=4118 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:firstboot_prop:s0 tclass=file permissive=1
03-20 19:39:21.425 I/main    (792): type=1400 audit(0.0:376): avc: denied { read } for name="u:object_r:persistent_properties_ready_prop:s0" dev="tmpfs" ino=4119 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:persistent_properties_ready_prop:s0 tclass=file permissive=1`
`03-20 19:39:37.722 W/ActivityManager(340): Background start not allowed: service Intent { cmp=ru.codedevice.iobrokerpawii/.connection.WebServerService (has extras) } to ru.codedevice.iobrokerpawii/.connection.WebServerService from pid=1279 uid=10110 pkg=ru.codedevice.iobrokerpawii
03-20 19:39:37.724 D/AndroidRuntime(1279): Shutting down VM
--------- beginning of crash
03-20 19:39:37.732 E/AndroidRuntime(1279): FATAL EXCEPTION: main
03-20 19:39:37.732 E/AndroidRuntime(1279): Process: ru.codedevice.iobrokerpawii, PID: 1279
03-20 19:39:37.732 E/AndroidRuntime(1279): java.lang.RuntimeException: Unable to start receiver ru.codedevice.iobrokerpawii.MainReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ru.codedevice.iobrokerpawii/.connection.WebServerService (has extras) }: app is in background uid UidRecord{e0333c2 u0a110 RCVR idle change:uncached procs:1 seq(0,0,0)}
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3195)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.os.Looper.loop(Looper.java:164)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.app.ActivityThread.main(ActivityThread.java:6499)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at java.lang.reflect.Method.invoke(Native Method)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
03-20 19:39:37.732 E/AndroidRuntime(1279): Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ru.codedevice.iobrokerpawii/.connection.WebServerService (has extras) }: app is in background uid UidRecord{e0333c2 u0a110 RCVR idle change:uncached procs:1 seq(0,0,0)}
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at ru.codedevice.iobrokerpawii.MainReceiver.onReceive(MainReceiver.java:53)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3188)
03-20 19:39:37.732 E/AndroidRuntime(1279): 	... 9 more
03-20 19:39:37.745 I/chatty  (1330): uid=0(root) com.android.contacts expire 9 lines
03-20 19:39:37.778 W/ActivityManager(340): Slow operation: 54ms so far, now at startProcess: returned from zygote!
03-20 19:39:37.778 W/ActivityManager(340): Slow operation: 54ms so far, now at startProcess: done updating battery stats
03-20 19:39:37.779 W/ActivityManager(340): Slow operation: 54ms so far, now at startProcess: building log message
03-20 19:39:37.779 I/ActivityManager(340): Start proc 1330:com.android.contacts/u0a10 for broadcast com.android.contacts/.interactions.OnBootOrUpgradeReceiver
03-20 19:39:37.779 W/ActivityManager(340): Slow operation: 54ms so far, now at startProcess: starting to update pids map
03-20 19:39:37.779 W/ActivityManager(340): Slow operation: 54ms so far, now at startProcess: done updating pids map
03-20 19:39:37.779 W/ActivityManager(340): Slow operation: 55ms so far, now at startProcess: done starting proc!
03-20 19:39:37.797 W/ContextImpl(340): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:966 com.android.server.am.AppErrors.crashApplicationInner:393 com.android.server.am.AppErrors.crashApplication:321 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:14573 com.android.server.am.ActivityManagerService.handleApplicationCrash:14555 
03-20 19:39:37.837 I/ActivityManager(340): Showing crash dialog for package ru.codedevice.iobrokerpawii u0
03-20 19:39:37.861 W/zygote  (1279): Unsupported class loader
03-20 19:39:37.865 W/zygote  (1279): Skipping duplicate class check due to unsupported classloader
`
`03-20 19:39:42.481 I/FA      (1279):   adb shell setprop debug.firebase.analytics.app ru.codedevice.iobrokerpawii
03-20 19:39:42.572 I/chatty  (1409): uid=10018(com.google.android.gms) com.google.android.play.games.ui expire 7 lines`
`03-20 19:39:50.387 I/ActivityManager(340): Killing 1279:ru.codedevice.iobrokerpawii/u0a110 (adj 904): crash
03-20 19:39:50.391 W/system_server(340): kill(-1279, 9) failed: No such process
03-20 19:39:50.428 I/zygote  (1675): The ClassLoaderContext is a special shared library.
03-20 19:39:50.438 W/system_server(340): kill(-1279, 9) failed: No such process
03-20 19:39:50.442 D/WificondControl(340): Scan result ready event
03-20 19:39:50.454 D/WificondScannerImpl(340): Filtering out 3 scan results.
03-20 19:39:50.471 I/GCoreUlr(777): Starting service, intent=Intent { act=com.google.android.location.reporting.WIFI_TRIGGERED_FLUSH_AND_UPLOAD cmp=com.google.android.gms/com.google.android.location.reporting.service.DispatchingService }, extras=null
03-20 19:39:50.473 I/WifiService(340): getConnectionInfo uid=10018
03-20 19:39:50.483 W/system_server(340): kill(-1279, 9) failed: No such process
03-20 19:39:50.491 W/zygote  (1675): ClassLoaderContext size mismatch. expected=1, actual=2 (PCL[/system/framework/com.android.media.remotedisplay.jar*818632460:/system/framework/com.android.location.provider.jar*2505365830] | PCL[/system/framework/com.android.media.remotedisplay.jar*818632460:/system/framework/com.android.location.provider.jar*2505365830];PCL[/data/dalvik-cache/xposed_XResourcesSuperClass.dex*2802528989:/data/dalvik-cache/xposed_XTypedArraySuperClass.dex*708326108])
03-20 19:39:50.518 W/InputEventReceiver(340): Attempted to finish an input event but the input event receiver has already been disposed.
03-20 19:39:50.519 W/ViewRootImpl[iobrokerpawii](340): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=867.6338, y[0]=514.0757, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=2, eventTime=72887, downTime=72857, deviceId=1, source=0x1002 }
03-20 19:39:50.519 W/ViewRootImpl[iobrokerpawii](340): Dropping event due to root view being removed: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=867.6338, y[0]=514.0757, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=72916, downTime=72857, deviceId=1, source=0x1002 }
03-20 19:39:50.519 I/chatty  (340): uid=1000(system) android.ui identical 1 line
03-20 19:39:50.519 W/InputEventReceiver(340): Attempted to finish an input event but the input event receiver has already been disposed.
03-20 19:39:50.530 W/system_server(340): kill(-1279, 9) failed: No such process`

**Comment by bondrogeen** [comment]
Send me an email bondrogeen@gmail.com

**Comment by Ilovegym66** [comment]
here the same, on Samsung Tab A, Samsung S8 and Samsung S9. Old version from here works fine, the version 1.3.1 or higher from google are crashing after press connection. All permissions are set.  Deinstall and install it back, the same. Cache deleted. My devices are NOT rooted.

**Comment by bondrogeen** [comment]
> here the same, on Samsung Tab A, Samsung S8 and Samsung S9. Old version from here works fine, the version 1.3.1 or higher from google are crashing after press connection. All permissions are set. Deinstall and install it back, the same. Cache deleted. My devices are NOT rooted.

I know about the problem, at the moment you can fix it
1 ) **completely remove** the old 1.15 application
2 ) install the new version >= 1.32.
3 ) update adapter >= 0.3.1
or
wait for the next update

**Comment by sabphil22** [comment]
Same problem here. 
Everytime i restarted the tablet, app autostart chrashed 
App is Version 1.34 
Adapter 0.3.2
Both are installed one week ago.

**Comment by bondrogeen** [comment]
Well, I'll check.
