### ISSUE TITLE
Display control not work

### ISSUE THREAD

**Issue by RichieXX** [bondrogeen/ioBroker.paw#35]
There is a another bug in iobroker adapter. I can not control display on/off with iobroker objects or scripts. Web control allready works perfectly. I there a way to control the tablet with web commands as workarround?

**Comment by bondrogeen** [comment]
Phone model and version of android?

**Comment by RichieXX** [comment]
This issue occurs on all my tablets (various Anfroid versions ... 7-8). I think, thats not a problem of the android app. I can switch screen on/off with androids app web interface perfectly. Only the iobroker adapter (objects and scripts) did'nt. I tried both variants (turnOnOff and toWake).

> I there a way to control the tablet with web commands as workarround?
about as: 
`http://<ip>:8080/?toWake=true`?

**Comment by bondrogeen** [comment]
If it works through the web interface, it should work through the objects too.


To wake the screen, use the toWake command.
You can do this:
1) through objects
**_paw.0.MiA2Lite.comm.display.toWake_**
send **true** or **false**
2) JS
**sendTo ("paw.0", 'all', {toWake: true});**
3) get or post request
**http://<ip>:8080/api/set.json?toWake=true**

**Comment by bondrogeen** [comment]
Wait for the next update, fixed the work of the function "toWake"
