### ISSUE TITLE
Update app on device: <Device>

### ISSUE THREAD

**Issue by RichieXX** [bondrogeen/ioBroker.paw#36]
Since new adapter version iobroker logs "warn: Update app on device: <Device>" with app version 1.33 from Playstore. Is there a newer version somewhere?

**Comment by bondrogeen** [comment]
One of these days I will publish a new version. Take your time, I need more time to test.)

**Comment by RichieXX** [comment]
OK. No Problem. I can wait.

**Comment by bondrogeen** [comment]
Updated

**Comment by BassT23** [comment]
Problem not fixed?
App 1.35
Adapter 0.3.2

**Comment by senger1985** [comment]
Same here
